### ISSUE TITLE
Story 02 - Business Definition

### ISSUE THREAD

**Issue by FranciscoLemos03** [FranciscoLemos03/Repo_T08#12]
### Description
In this story it is necessary to create a business process and a domain model

### Acceptance Criteria
- [ ] The Business process need to have description of PNs supported by the system.
- [ ] The Business process need to Include the modeling of one or more BPs with BPMN diagrams.
- [ ] In the Domain Model, you must have an initial UML Class Diagram to capture the business entities.
- [ ] The Domain Model must have a Definition of concepts, terms and entities.

### Tasks
- [ ] 1
- [ ] 2

### Estimate
6 Horas

---

**Assigned to:**
- [ ] @FranciscoLemos03 
- [ ] @bolycao 
- [ ] @ruijor
