### ISSUE TITLE
Story 03

### ISSUE THREAD

**Issue by FranciscoLemos03** [FranciscoLemos03/Repo_T08#19]
### Description
Create a CDU Model, Business Rules, RNF and AC's

### Acceptance Criteria
- [ ] Use case diagram by component
- [ ] List of use cases
- [ ] Business rules including their description / specification

### Tasks
- [ ] Task 10
- [ ] Task 11
- [ ] Task 12

### Estimate
9 Hours

---

**Assigned to:**
- [ ] @FranciscoLemos03 
- [ ] @bolycao 
- [ ] @ruijor
