### ISSUE TITLE
Sprint 04

### ISSUE THREAD

**Issue by FranciscoLemos03** [FranciscoLemos03/Repo_T08#23]
### Description
Create technical arquitecture, backlog preparation and develop the first version of the class diagram

### Acceptance Criteria
- [ ] Create technical arquitecture with the technical components and graphical representation of architecture
- [ ] List CdU ordered by priority
- [ ] Prepare project plan
- [ ] Class Diagram 

### Tasks
- [ ] TASK 13
- [ ] TASK 14
- [ ] TASK 15

### Estimate
8H
