### ISSUE TITLE
Story 01 - Project Vision

### ISSUE THREAD

**Issue by FranciscoLemos03** [FranciscoLemos03/Repo_T08#5]
### Description
Do the Project Vision to understand the project goal

### Tasks
- [ ] [Context Diagram and Actors]
- [ ] [Project Description]
- [ ] [Business Goal and Objective]
- [ ] [Stakeholder description]
- [ ] [High level features by component]

### Estimate
4 hours

---

**Responsáveis:**
- @bolycao 
- @FranciscoLemos03
- @ruijor
